---
booktitle: Proceedings of the 26th Conference on Uncertainty in Artificial Intelligence
shortname: UAI
year: '2010'
start: 2010-07-08
end: 2010-07-11
conference_number: '26'
published: 2026-10-04
volume: R8
firstpublished: 2010-07-08
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: UAI-2010
month: 0
cycles: false
bibtex_editor: Gr{\"u}nwald, Peter and Spirtes, Peter
editor:
- given: Peter
  family: Grünwald
- given: Peter
  family: Spirtes
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 26th Conference on Uncertainty in Artificial Intelligence
    Held in Catalina Island, CA, USA on 08-11 July 2010

  Published as Reissue 8 by the Proceedings of Machine Learning Research on 04 October 2026.

  Volume Edited by:
    Peter Grünwald
    Peter Spirtes

  Series Editors:
    Tegan Emerson
    Hoel Kervadec
    Neil D. Lawrence
date_str: '08--11 Jul'
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/r8"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: r8
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Reissue
volume_dir: r8
email: ''
conference:
  name: Uncertainty in Artificial Intelligence
  url: https://event.cwi.nl/uai2010/
  location: Catalina Island, CA, USA
  dates:
  - 2010-07-08
  - 2010-07-09
  - 2010-07-10
  - 2010-07-11
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: uai2010_clean.bib
# Site settings
# Original source:  uai2010_clean.bib